const colors = {
  light: {
    text: "#0A0A0A",
    tint: "#0A0A0A",
    background: "#F7F7F7",
    foreground: "#0A0A0A",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    primary: "#0A0A0A",
    primaryForeground: "#FFFFFF",
    secondary: "#F3F3F3",
    secondaryForeground: "#0A0A0A",
    muted: "#F3F3F3",
    mutedForeground: "#737373",
    accent: "#0A0A0A",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E8E8E8",
    input: "#E8E8E8",
    success: "#16A34A",
    successForeground: "#FFFFFF",
    warning: "#D97706",
    warningForeground: "#FFFFFF",
    info: "#2563EB",
    infoForeground: "#FFFFFF",
  },
  dark: {
    text: "#FAFAFA",
    tint: "#FAFAFA",
    background: "#0A0A0A",
    foreground: "#FAFAFA",
    card: "#141414",
    cardForeground: "#FAFAFA",
    primary: "#FAFAFA",
    primaryForeground: "#0A0A0A",
    secondary: "#1C1C1C",
    secondaryForeground: "#FAFAFA",
    muted: "#1C1C1C",
    mutedForeground: "#737373",
    accent: "#FAFAFA",
    accentForeground: "#0A0A0A",
    destructive: "#EF4444",
    destructiveForeground: "#FAFAFA",
    border: "#242424",
    input: "#242424",
    success: "#22C55E",
    successForeground: "#0A0A0A",
    warning: "#F59E0B",
    warningForeground: "#0A0A0A",
    info: "#3B82F6",
    infoForeground: "#FAFAFA",
  },
  radius: 10,
};

export default colors;
